application: ner-monty
version: 3
runtime: python27
api_version: 1
threadsafe: yes
handlers:
- url: /assets
  static_dir: assets
- url: /assets_new
  static_dir: assets_new
- url: /superadmin.*
  script: superadmin.app
  login: admin
- url: /.*
  script: main.app
- url: /_ah/bounce
  script: handle_bounced_email.app
  login: admin
builtins:
- appstats: on
libraries:
- name: webapp2
  version: "2.5.2"
inbound_services:
- mail_bounce