application: apm-eternus
version: eternus
runtime: python27
api_version: 1
threadsafe: yes
handlers:
- url: /assets
  static_dir: assets
- url: /superadmin/.*
  script: superadmin.app
  login: admin
- url: /.*
  script: main.app
- url: /_ah/bounce
  script: handle_bounced_email.app
  login: admin

libraries:
- name: webapp2
  version: "2.5.2"
inbound_services:
- mail_bounce